"""Rebuild original imports elsewhere and compare every generated byte."""
import argparse
import hashlib
import json
from pathlib import Path
from import_factory import run, DataParser

def verify(args):
    for text in ('Map={a=1,a=2}', 'Map={a=os.execute("bad")}', 'Map={} function evil() end', 'Map={a=0/0}'):
        try: DataParser(text).document()
        except (ValueError,IndexError): pass
        else: raise AssertionError('Executable or malformed data accepted: '+text)
    assert DataParser('Map={sample={type="World",position={1,2,3},static=true}}').document()['sample']['position']==[1,2,3]
    run(argparse.Namespace(legacy_root=args.legacy_root,output_root=args.work_root/'output',work_root=args.work_root/'ogre'))
    files=list((args.work_root/'output').rglob('*'));checked=0
    for file in files:
        if not file.is_file(): continue
        relative=file.relative_to(args.work_root/'output')
        assert file.read_bytes()==(args.reference_root/relative).read_bytes(),f'Nonreproducible output: {relative}'
        checked+=1
    manifest=json.loads((args.reference_root/'factory_scene.json').read_text())
    for name,digest in manifest['sources'].items():
        assert hashlib.sha256((args.legacy_root/name).read_bytes()).hexdigest()==digest,f'Source changed: {name}'
    report={'generated_files_identical':checked,'source_hashes_verified':len(manifest['sources']),'restricted_parser_negative_controls':4,'meshes':len(manifest['meshes'])}
    (args.work_root/'verification.json').write_text(json.dumps(report,indent=2));print(json.dumps(report))

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    for name in ('legacy-root','reference-root','work-root'): parser.add_argument('--'+name,type=Path,required=True)
    args=parser.parse_args()
    if args.work_root.resolve()==args.reference_root.resolve() or args.reference_root.resolve() in args.work_root.resolve().parents:
        parser.error('Verification output must be separate from checked-in assets')
    verify(args)
