"""Rebuild the bounded VFX translation and verify generated bytes and provenance."""
import argparse
import hashlib
import json
from pathlib import Path
from import_effects import run

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    for name in ('legacy-root', 'reference-root', 'work-root'):
        parser.add_argument('--'+name, type=Path, required=True)
    args = parser.parse_args()
    reference = args.reference_root.resolve()
    work = args.work_root.resolve()
    if reference == work or reference in work.parents or work in reference.parents:
        parser.error('Verification requires a separate output directory')
    run(args.legacy_root, work)
    generated = sorted(p.relative_to(work) for p in work.rglob('*') if p.is_file())
    expected = sorted(p.relative_to(reference) for p in reference.rglob('*') if p.is_file())
    if generated != expected:
        raise ValueError('Generated file inventory changed')
    for relative in generated:
        if (work/relative).read_bytes() != (reference/relative).read_bytes():
            raise ValueError('Output changed: '+str(relative))
    manifest = json.loads((reference/'manifest.json').read_text())
    for path, digest in manifest['sources'].items():
        if hashlib.sha256((args.legacy_root/path).read_bytes()).hexdigest() != digest:
            raise ValueError('Source changed: '+path)
    print(json.dumps({'identical_generated_files': len(generated),
                      'verified_sources': len(manifest['sources'])}))
