file(MAKE_DIRECTORY "${OUTPUT}")
execute_process(COMMAND "${EXECUTABLE}" --ui-review "${OUTPUT}" RESULT_VARIABLE result OUTPUT_VARIABLE log ERROR_VARIABLE errors TIMEOUT 100)
file(WRITE "${OUTPUT}/capture.log" "${log}\n${errors}")
if(NOT result EQUAL 0 OR "${log}${errors}" MATCHES "VUID-|Validation Error|Diligent Engine: (Error|ERROR)")
    message(FATAL_ERROR "UI Vulkan capture failed: ${result}\n${errors}")
endif()
foreach(width 1280 1920 2560)
    foreach(page RANGE 0 16)
        if(NOT EXISTS "${OUTPUT}/${width}/page-${page}.ppm")
            message(FATAL_ERROR "Missing UI capture: ${width}/${page}")
        endif()
    endforeach()
endforeach()
if(DEFINED COMPARATOR)
    execute_process(COMMAND "${COMPARATOR}" "${OUTPUT}" "${REFERENCES}" --ui RESULT_VARIABLE compared OUTPUT_VARIABLE differences ERROR_VARIABLE comparison_error)
    file(WRITE "${OUTPUT}/comparison.log" "${differences}\n${comparison_error}")
    if(NOT compared EQUAL 0)
        message(FATAL_ERROR "UI image regression failed: ${comparison_error}")
    endif()
endif()
