if(WIN32)
    file(GLOB ssl_runtime "${OPENSSL_BIN}/libssl*.dll" "${OPENSSL_BIN}/libcrypto*.dll")
    list(LENGTH ssl_runtime count)
    if(NOT count EQUAL 2)
        message(FATAL_ERROR "Expected the OpenSSL SSL and Crypto runtime DLLs in ${OPENSSL_BIN}")
    endif()
    file(COPY ${ssl_runtime} DESTINATION "${PACKAGE_DIR}")
    if(NOT EXISTS "${OPENSSL_BIN}/simdjson.dll")
        message(FATAL_ERROR "Expected the simdjson runtime DLL in ${OPENSSL_BIN}")
    endif()
    file(COPY "${OPENSSL_BIN}/simdjson.dll" DESTINATION "${PACKAGE_DIR}")
endif()
