file(MAKE_DIRECTORY "${GLOOM_CAPTURE_DIR}")
set(mode --visual-review)
set(comparison_options)
if(GLOOM_FACTORY_REVIEW)
    set(mode --factory-review)
    set(comparison_options --factory)
endif()
if(GLOOM_CHARACTER_REVIEW)
    set(mode --character-review)
    set(comparison_options --characters)
endif()
execute_process(COMMAND "${GLOOM_EXECUTABLE}" ${mode} "${GLOOM_CAPTURE_DIR}"
    RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 35)
file(WRITE "${GLOOM_CAPTURE_DIR}/render.log" "${stdout}\n${stderr}")
if(NOT result EQUAL 0 OR "${stdout}\n${stderr}" MATCHES "Diligent Engine: ERROR|VUID-|Diligent Engine: Error")
    message(FATAL_ERROR "Visual capture failed: ${result}. See ${GLOOM_CAPTURE_DIR}/render.log")
endif()
execute_process(COMMAND "${GLOOM_COMPARATOR}" "${GLOOM_CAPTURE_DIR}" "${GLOOM_REFERENCE_DIR}" ${comparison_options}
    RESULT_VARIABLE result OUTPUT_VARIABLE report ERROR_VARIABLE errors TIMEOUT 10)
file(WRITE "${GLOOM_CAPTURE_DIR}/comparison.txt" "${report}\n${errors}")
message(STATUS "${report}")
if(NOT result EQUAL 0)
    message(FATAL_ERROR "${errors}")
endif()
